#!/usr/bin/perl -w
#========================================================================
#
# objc2perl 
#
# DESCRIPTION
#                                                                       
# objc2perl is a objc2 perl wrapper package                            
#
# AUTHOR
#   v-zor <elvish.archwizard@gmail.com> 
#
# COPYRIGHT
#   Copyright (C) 2013 v-zor  
#   All Rights Reserved.
#
#   This module is free software; you can redistribute it and/or
#   modify it under the same terms as Perl itself.
#
#------------------------------------------------------------------------
#
# $Id: objc2perl,v 1.3 2003/04/07 16:16:42 v-zor Exp $
#
# $Log: objc2perl,v $
#
# Revision 0.1.1  2013/09/06 03:59:42  v-zor
# Adding CPAN module code 
#
#========================================================================

package ObjC2Perl;

use strict;
use Getopt::Long;                       # Basic cmdline arg handling
use FileHandle;                         # 

my $NAME     = "objc2perl";
my $HOME     = $ENV{ HOME } || '';
my $VERSION;
$VERSION  = '0.00';

my %versions;
$versions{objc2perl} = '$Revision: 0.1 $ ';  

#print STDERR "Starting main program\n" if ($opt_debug>1);

__END__


=head1 NAME

objc2perl - ObjC2Perl 

=head1 SYNOPSIS

objc2perl [options] [ [ args ] ]

 Options:
   -V, --version                 display version, then exit
   -h, --help                    print usage, then exit
       --man                     display manual (POD)
   -d, --debug=integer           show debug messages

=head1 DESCRIPTION

B<objc2perl> 


=head1 OPTIONS

=over 8

=item B<-V, --version>

Prints the version and exits

=item B<-h, --help>

Prints a brief help message

=item B<--man>

Prints a manual page (detailed help).

=item B<-d, --debug>

Prints debug messages

=back

See B<objc2perl> for a summary of options.



=head1 PREREQUISITES

This script requires the C<strict> module.  It also requires
C<foobar 1.00>.


=head1 COREQUISITES

CGI

=head1 SCRIPT CATEGORIES

CPAN/Administrative
Fun/Educational

=head1 BUGS

None known.

=head1 VERSION

0.0.1Distributed as part of Valor's Endversion 0.0.1, released on .

=head1 SEE ALSO

L<frost|atlas>

=head1 AUTHOR

v-zor E<lt>elvish.archwizard@gmail.comE<gt>

=head1 COPYRIGHT

Copyright (C) 2013 v-zor.
All Rights Reserved.

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=head1 REVISION

Revision: $Revision: 0.1 $

=cut



